# Schema for the configuration files of the adstxt module.
adstxt.settings:
  type: config_object
  label: 'Ads.txt settings'
  mapping:
    content:
      type: string
      label: 'Contents of ads.txt'
